---
# tasks file for openvpn_node_exporter
- name: Install GO
  apt:
    name: "golang"
    state: "latest"

- name: Download openvpn node exporter
  get_url:
    url: "https://github.com/kumina/openvpn_exporter/archive/refs/tags/v0.3.0.tar.gz"
    dest: "~/Downloads/"

- name: Extract archive openvpn node exporter
  command: "tar -xzvf openvpn_exporter-0.3.0.tar.gz"
  args:
    chdir: "~/Downloads"

- name: Copy main.go file to folder
  copy:
    src: "main.go"
    dest: "~/Downloads/openvpn_exporter-0.3.0"

- name: Build the exporter
  shell: "go build -o openvpn_exporter main.go"
  args:
    chdir: "~/Downloads/openvpn_exporter-0.3.0" 

- name: Copy binary openvpn_exporter to /usr/local/bin/
  copy:
    src: "~/Downloads/openvpn_exporter-0.3.0/openvpn_exporter"
    dest: "/usr/local/bin/"
    mode: 0755

- name: install service
  copy:
    src: openvpn_exporter.service
    dest: /etc/systemd/system
    owner: root
    group: root
    mode: 0755
  notify: reload_daemon_and_restart_openvpn_exporter
