---
# defaults file for ansible-borg
backup_server: 192.168.244.179
backup_user: borg
protocol: ssh
backup_port: 22
backup_encryption_method: repokey
backup_delete: false
backup_create: true
systemd_target_dir: /etc/systemd/system/
borg_systemd_on_failure: ""

backup_prune_dryrun: false
backup_prune_force: false
backup_prune_stats: true
backup_prune_list: true
backup_prune_save_space: false

# systemd specific parameters
systemd_script_mode: 0774
systemd_script_user: root
borg_systemd_user: root
borg_systemd_group: root
systemd_service_mode: 0644

