- name: initialize borg if not already done
  block:
    - name: check status of borg repo
      shell: "borg info {{ target_location }}"
      ignore_errors: yes
      
  rescue:
    - name: initialize borg
      become: yes
      command: "borg init -e none {{ target_location }}"
        
